apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kash-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/KashifSad/argocd-tutorial.git
    targetRevision: HEAD
    path: day1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
